source "https://rubygems.org"

gem "pry", "~> 0.14.1"

gem "rack", "~> 2.2"
gem "json", "~> 2.5"
gem "shotgun", "~> 0.9.2"

gem "rack-cors", "~> 1.1"

gem "activerecord", "~> 6.1"
gem "sinatra-activerecord", "~> 2.0"

gem "sqlite3", "~> 1.4"
 

gem "rack-test", "~> 1.1"

gem "rspec", "~> 3.10"
gem "require_all"
